### ISSUE TITLE
RDS baseline?

### ISSUE THREAD

**Issue by hamishivi** [princeton-nlp/LESS#29]
Hi, do you have an implementation of the RDS baseline mentioned in the paper in this codebase? From a quick look, I couldn't find anything. If not, would it be possible to share your RDS implementation? Thanks!

**Comment by xiamengzhou** [comment]
Hi @hamishivi 
You can use the `collect_reps` from [this script](https://github.com/princeton-nlp/LESS/blob/main/less/data_selection/collect_grad_reps.py) to collect representations instead of gradients. It should work with [this script](https://github.com/princeton-nlp/LESS/blob/main/less/scripts/get_info/grad/get_eval_lora_grads.sh) by changing the `--info_type` to `reps`. 

After collecting the representations, you can run the selection process similar to gradient selection.

**Comment by hamishivi** [comment]
@xiamengzhou Awesome, thanks!
